# Site settings
title: ZYL Notepad
# email: 
# description: ""
baseurl: ""
url: "http://pay4trip.bid"
# twitter_username: none
github_username:  zyl22

encoding: UTF-8

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge